services:
  db:
    container_name: client_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clientdb
    ports:
      - "5432:5432"
  app:
    container_name: client_app
    build:
      context: .
      dockerfile: ./Client/Dockerfile
    ports:
      - "10000:8080"
    depends_on:
      - client_db
